language: ruby
rvm:
  - 2.1

script: bundle exec jekyll build --destination _site/public-domain && bundle exec htmlproof ./_site --disable-external --allow-hash-href

branches:
  only:
    - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
